on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubutu-latest

    steps:
      - name: 'Testing Githup action'
        run: pwd

      - name: 'Testing Printing'
        run: echo Ahmed
