on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login to docker hub"
        run: docker login --username a7hmedhamdy --password dckr_pat_B4iWaxAyHSKPbjLCV7Ze005vkXI
      - name: "Building docker image"
        run: docker build -t a7hmedhamdy/myimage

      - name: "pushing to docker hub"
        run: docker push a7hmedhamdy/myimage
